### ISSUE TITLE
Translation Progress (docs/guides)

### ISSUE THREAD

**Issue by hirotaka** [hirotaka/supabase-ja#7]
## 翻訳者へ

ページを翻訳するために:

1. あなたが翻訳したいページについて、以下のチェックリストとコメント欄を見て、他の誰も翻訳することを宣言していないことを確認してください。
1. このIssueに、翻訳したいページ名をコメントしてください。1 ページづつでお願いします。
1. supabase-jaリポジトリをCloneして、該当するページを翻訳しましょう！
    1. [翻訳ガイド](https://github.com/hirotaka/supabase-ja/blob/d62be14c4d95a497ab540507de3c0dee5e2a90f9/TRANSLATION.md)に目を通してください。
    1. 翻訳した文章を音読してみましょう。明らかに不自然な表現を見つけやすくなります。
    1. 表現で迷ったらDisucussionsで相談してみましょう！
1. 翻訳と校正を終えたら、Pull Requestを送りましょう！
    1. Allow edits from maintainerにチェックを入れるのを忘れずに。
    1. しばらく待ってもレビューが終わらなかったり、必要なレビュー数が足りない状態が続いた場合は、メンテナーの誰かに@を付けてメンションを飛ばしてください。

自分で宣言したページは早めに翻訳してください！：もし、時間の都合が取れなくなったり、進めなくなったりしたら、他の人に振れるようにするために、メンテナーの誰かにお知らせください。

### メンテナー
- @hirotaka

## 翻訳済みページ
<details>
<summary>開く/閉じる</summary>

- [x] #116 going-into-prod.mdx @hirotaka
- [x] #115  guides/integrations/auth0.mdx @hirotaka
- [x] #114 guides/handbook/supasquad.mdx @hirotaka
- [x] #113 guides/integrations/prisma.mdx @hirotaka
- [x] #112 faq.md @hirotaka
- [x] #111 guides/handbook/contributing.mdx @hirotaka
- [x] #110 guides/integrations/draftbit.mdx @hirotaka
- [x] #108 guides/integrations/vercel.mdx @hirotaka
- [x] #106 guides/database/full-text-search.mdx @hirotaka
- [x] #105 guides/database/replication.mdx @hirotaka
- [x] #104 guides/database/managing-timezones.mdx @hirotaka
- [x] #103 guides/database/managing-passwords.mdx @hirotaka
- [x] #102 guides/database/timeouts.mdx @hirotaka
- [x] #101 guides/database/connecting/connection-pooling.md @hirotaka
- [x] #100 guides/database/connecting/connecting-to-postgres.mdx @hirotaka
- [x] #99 guides/database/extensions/uuid-ossp.mdx @hirotaka
- [x] #98 guides/database/extensions/http.md @hirotaka
- [x] #95 guides/database/functions.mdx @hirotaka
- [x] #94 guides/database/extensions/plv8.md @hirotaka
- [x] #92 guides/database/connecting/direct-connections.mdx @hirotaka
- [x] #91 guides/database/extensions.mdx @hirotaka
- [x] #90 guides/database/intro.mdx @hirotaka
- [x] #90 guides/database/tables.mdx @hirotaka
- [x] #89 guides/auth/auth-messagebird.mdx @hirotaka
- [x] #88 guides/auth/auth-twilio.mdx @hirotaka
- [x] #87 guides/auth/auth-apple.mdx @hirotaka
- [x] #86 guides/auth/auth-twitch.mdx @hirotaka
- [x] #85 guides/auth/auth-spotify.mdx @hirotaka
- [x] #84 guides/auth/auth-slack.mdx @hirotaka
- [x] #83 guides/auth/auth-google.mdx @hirotaka
- [x] #82 guides/auth/auth-gitlab.mdx @hirotaka
- [x] #80 guides/auth/auth-facebook.mdx @hirotaka
- [x] #79 guides/auth/auth-discord.mdx @hirotaka
- [x] #78 guides/auth/auth-bitbucket.mdx @hirotaka
- [x] #75 guides/auth/auth-twitter.mdx @hirotaka
- [x] #74 guides/auth/auth-github.mdx @hirotaka
- [x] #73 guides/auth/auth-magic-link.mdx @hirotaka
- [x] #72 guides/auth/auth-email.mdx @hirotaka
- [x] #70 guides/auth/intro.mdx @hirotaka
- [x] #69 guides/examples.mdx @hirotaka
- [x] #68 guides/hosting/overview.mdx @hirotaka
- [x] #67 guides/hosting/platform.mdx @hirotaka
- [x] #67 guides/hosting/docker.mdx @hirotaka
- [x] #64 guides.md @hirotaka
- [x] #63 guides/local-development.mdx @hirotaka
- [x] #42 guides/auth/managing-user-data.mdx @hirotaka
- [x] #41 guides/auth/row-level-security.mdx @hirotaka
- [x] #39 learn/auth-deep-dive/google-oauth.md @hirotaka
- [x] #35 learn/auth-deep-dive/gotrue.md @hirotaka
- [x] #32 learn/auth-deep-dive/policies.md @hirotaka
- [x] #30 guides/with-svelte.mdx @hirotaka
- [x] #29 guides/with-redwoodjs.mdx @hirotaka
- [x] #23 guides/with-flutter.mdx @hirotaka
- [x] #22 guides/with-angular.mdx @hirotaka
- [x] #21 guides/with-vue-3.mdx @hirotaka
- [x] #20 guides/with-react.mdx @hirotaka
- [x] #19 guides/with-nextjs.mdx @hirotaka
- [x] #15 guides/examples.mdx @hirotaka
- [x] #13 guides/storage.mdx @hirotaka
- [x] #12 guides/api.mdx @hirotaka
- [x] #11 guides/auth.mdx @hirotaka
- [x] #10 guides/database.mdx @hirotaka
- [x] #9 architecture.mdx @hirotaka
- [x] #8 about.mdx @hirotaka
- [x] #5 learn/auth-deep-dive/jwts.md @hirotaka
- [x] #4 learn/auth-deep-dive/row-level-security.md @hirotaka

</details>

### Hold 
- company/aup.md
- company/privacy.md
- company/terms.md

### Obsoletes
- guides/database/arrays.mdx
- guides/database/json.mdx
- guides/database/sql-to-api.mdx
- guides/database/extensions/pgtap.mdx
- guides/handbook/introduction.mdx
- support.md
